# -*- mode: ruby -*-
# vi: set ft=ruby :

# Import configuration
require 'yaml'
current_dir    = File.dirname(File.expand_path(__FILE__))
vagrant_config = YAML.load_file("#{current_dir}/config.yaml")

Vagrant.configure("2") do |config|
  config.vm.box       = "#{vagrant_config['root_folder']}/#{vagrant_config['box_name']}"
  config.ssh.username = vagrant_config['ssh_username']
  config.ssh.password = vagrant_config['ssh_password']

  # Do not map any folders
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Expose Ports
  config.vm.network "forwarded_port", guest: 8080, host: 8080
end
