# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
current_dir    = File.dirname(File.expand_path(__FILE__))
vagrant_config = YAML.load_file("#{current_dir}/config.yaml")

Vagrant.configure("2") do |config|
  config.vm.box         = "kreditorforeningen/ubuntu-focal"
  config.vm.box_version = "0.0.1"

  config.ssh.username = vagrant_config['ssh_username']
  config.ssh.password = vagrant_config['ssh_password']

  # Do not map any folders
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Expose Ports
  config.vm.network "forwarded_port", guest: 8080, host: 8080
end
